version: "3.7"
services:
  postgres:
    image: postgres:11
    ports:
      - 5641:5432
    env_file:
      - ./env/postgres.env
    network_mode: bridge
    volumes:
      - data:/data

  stellar-core:
    build:
      context: ./stellar-core
    depends_on:
      - postgres
    ports:
      - 11625:11625
      - 11626:11626
    env_file:
      - env/stellar-core.env
    network_mode: bridge
    volumes:
      - data:/data
      - ./assets/stellar-core:/assets

  stellar-horizon:
    build:
      context: ./stellar-horizon
    depends_on:
      - postgres
      - stellar-core
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - env/stellar-horizon.env
    network_mode: bridge
    volumes:
      - data:/data
      - ./assets/stellar-horizon:/assets
    command:
      - "--apply-migrations"
      - "--tls-cert"
      - "/assets/stellar-horizon.crt"
      - "--tls-key"
      - "/assets/stellar-horizon.key"

  stellar-bridge:
    build:
      context: ./stellar-bridge
    depends_on:
      - postgres
      - stellar-horizon
    restart: on-failure
    ports:
      - "8006:8006"
    env_file:
      - env/stellar-bridge.env
    network_mode: bridge
    volumes:
      - data:/data
      - ./assets/stellar-bridge:/assets

  stellar-compliance:
    build:
      context: ./stellar-compliance
    depends_on:
      - postgres
      - stellar-horizon
      - stellar-bridge
    restart: on-failure
    ports:
      - "8001:8001"
      - "8002:8002"
    env_file:
      - env/stellar-compliance.env
    network_mode: bridge
    volumes:
      - data:/data
      - ./assets/stellar-compliance:/assets

  stellar-federation:
    build:
      context: ./stellar-federation
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "8003:8003"
    env_file:
      - env/stellar-federation.env
    network_mode: bridge
    volumes:
      - data:/data
      - ./assets/stellar-federation:/assets

  web-auth-server:
    image: blocktop/mp-web-auth-server
    ports:
      - "3000:3000"
    env_file:
      - env/web-auth-server.env
    network_mode: bridge
    volumes:
      - ./assets/web-auth-server:/assets

  transfer-server:
    image: blocktop/mp-transfer-server
    ports:
      - "3001:3001"
    env_file:
      - env/transfer-server.env
    network_mode: bridge
    volumes:
      - ./assets/transfer-server:/assets

  web-server:
    image: blocktop/mp-web
    ports:
      - "3002:3002"
    env_file:
      - env/web.env
    network_mode: bridge
    volumes:
      - ./assets/web:/assets

volumes:
  data:
    external:
      name: data-volume
